# Generated by Django 4.2.9 on 2024-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('created_date', models.DateField()),
            ],
        ),
    ]
