# Generated by Django 4.2.9 on 2024-01-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask_app', '0003_dailytaskdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytaskdetails',
            old_name='daily_task',
            new_name='DailyTask',
        ),
        migrations.AlterField(
            model_name='dailytaskdetails',
            name='task_description',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
