# Generated by Django 4.2.9 on 2024-01-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask_app', '0004_rename_daily_task_dailytaskdetails_dailytask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytaskdetails',
            old_name='DailyTask',
            new_name='task_id',
        ),
    ]
